import {
  THEME_PRESETS,
  type ThemePreset,
} from "./theme-presets.generated";

export type { ThemePreset };

export type ThemeType = {
  preset: string;
  radius: string;
  scale: string;
  contentLayout: string;
};

export const DEFAULT_THEME: ThemeType = {
  preset: "default",
  radius: "default",
  scale: "none",
  contentLayout: "full",
};

/**
 * Selectable presets. `styles/themes.css` is the source of truth; this list is
 * generated by `bun run themes:generate`. "default" falls back to `:root`.
 */
export const THEMES: ThemePreset[] = [
  { name: "Default", value: "default", colors: ["oklch(0.5 0 0)"] },
  ...THEME_PRESETS,
];
