services:
  app:
    image: localhost/ai-starter:latest
    ports:
      - "3000:3000"
    env_file:
      - ../.env.podman
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../public:/app/public
    restart: unless-stopped

  db:
    image: docker.io/postgres:18-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_starter_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
